### ISSUE TITLE
KB5 Edge2D demo is broken

### ISSUE THREAD

**Issue by jacklovell** [cherab/jet#10]
The demos/diagnostic/kb5/edge2d_to_kb5.py demo is broken, in 2 ways:
1. It tries to import `PythonFunction3D` from Raysect, which has moved in the latest Raysect and isn't intended to be public.
2. It imports from `cherab.edge2d`, which is not a publicly available sub package of Cherab.

1) is pretty easy to solve, as `PythonFunction3D` isn't used anywhere in the script so the import can just be removed. For 2), we should either make the Edge2D sub package available publicly or remove this demo from the JET package.

By the way, the cherab-edge2d package in `~mcarr/cherab/cherab_edge2d` on Freia is also broken with the latest Raysect release, as `Discrete2DMesh` has moved. But that's not a cherab-jet issue...

**Comment by vsnever** [comment]
Sorry for not informing you earlier, a few months ago I created a new Edge2D sub package using the development branch of SOLPS module as a template. Since the source code of the old @mattngc's Edge2D module was not used, the new package can be published under the same license as the SOLPS module. The module loads Edge2D simulation from `tranfile` using the EPROC interface to Python. There are a few things I want to improve, but the package can already be used as it is. 

I would be happy if you add this sub-package to the https://github.com/cherab. Here is the repo: https://github.com/vsnever/cherab-edge2d.

**Comment by jacklovell** [comment]
Thanks @vsnever. I've imported your version of `cherab-edge2d` into the Cherab organisation here on Github: see https://github.com/cherab/edge2d. I'll then fix this particular demo so it works with the cherab-edge2d subpackage.

**Comment by jacklovell** [comment]
Fixed in 4dd9ca8.
