### ISSUE TITLE
Update default path to CAD files

### ISSUE THREAD

**Issue by vsnever** [cherab/jet#24]
The path `/projects/cadmesh/` does not exist on JET Data Center computing nodes. However, the path `/common/cadmesh/` works for both UKAEA and JDC nodes. I suggest updating the default for `CADMESH_PATH` to `/common/cadmesh/`.

**Comment by jacklovell** [comment]
`/projects/cadmesh` on Freia and Heimdall is actually a symlink to `/common/projects/cadmesh`, and this is the correct directory to use since it contains the meshes for all the machines Cherab supports, not just JET. `/common/cadmesh` doesn't exist at all on Freia - the other UKAEA cluster - so would restrict use of cherab-jet to Heimdall and JDC only unless a user manually overrides  the path. Does `/common/projects/cadmesh` exist on JDC?

**Comment by vsnever** [comment]
Sorry, didn't know that, thanks. Unfortunately, `/common/projects` does not exist on JDC nodes. Probably, because the JDC is restricted to JET data only. Should we check for `/common/projects/cadmesh` first and if it does not exist, check for the `/common/cadmesh/` then?

**Comment by jacklovell** [comment]
Fixed by #29.
