### ISSUE TITLE
Does KB1 really need a special calculate_etendue function?

### ISSUE THREAD

**Issue by jacklovell** [cherab/jet#8]
There is a special `calculate_etendue` function for KB1, because the JET vessel acts as the aperture and so the `BolometerFoil.calculate_etendue` method gives misleading results (rays hitting the bottom of the vessel are not considered to have passed through the aperture). Would it not be simpler to CSG subtract the lower half of the vessel away and use the standard etendue method instead? Need to check that `Subtract(Mesh, Box)` works this way.

**Comment by CnlPepper** [comment]
You could just add a ray max depth to the method and pass it through the Ray(). It'll only check for collisions within that range,

**Comment by jacklovell** [comment]
Thanks, I'll try that.

**Comment by mattngc** [comment]
Yeah, I think you can understand why it was custom (one of Matt's usual hack jobs :)). I think you really need to be careful with this reguardless of how you do it. The issue is that the full aperture is not a simple mesh file. You need to inject some special knowledge somewhere (i.e. CSG or max ray-depth, etc) otherwise it will definitely give you wrong results. The standard method will only work for systems without further occlusion beyond the pinhole. Anything beyond that is a more compount system.

**Comment by jacklovell** [comment]
I have to take the blame for this hack job, I'm afraid! But yes, I agree that this is a somewhat special case. I think adding an optional max ray depth to the `calculate_etendue` method will generalise it significantly, and so make it more useful for situations like KB1.

**Comment by jacklovell** [comment]
For the avoidance of confusion, @CnlPepper you mean `ray.max_distance` rather than `ray.max_depth`, right?

**Comment by jacklovell** [comment]
Fixed by #9
